### ISSUE TITLE
Merge @plusCubed's fork?

### ISSUE THREAD

**Issue by developit** [developit/preact-cli-plugin-async#14]
Would it be worth merging @plusCubed's fork that switches to fast-async under the hood?
The output size of fast-async is slightly larger due to additional promise wrappers, but it's also much more reliable.  I believe this would fix #11 and #2.

The fork: https://github.com/plusCubed/preact-cli-plugin-fast-async

**Comment by developit** [comment]
Daniel - I'd be happy to make you a contributor on this repo and give you npm publish rights, if you're interested.

**Comment by reznord** [comment]
I'm totally in for it....merging that fork into the master.

**Comment by pluscubed** [comment]
@developit Sure, I'd be happy to - it's just a one-line change. I recall someone on Slack had some concerns about the size increasing significantly, though I haven't observed that in my projects.

**Comment by newtriks** [comment]
I found that this plugin was the source of the following error `message: "The XMLHttpRequest compatibility library was not found."` that I came up against when integrating Firebase into an app generated using `preact-cli`. Switching to @plusCubed repos fixed this issue 👍

**Comment by developit** [comment]
Done! I checked and it looks like the size overhead is super minimal - adding an async/await fetch() call to the default scaffolded "simple" app is around 70 bytes!

@plusCubed your fork is actually more popular than my original plugin, so we might just want to steer users to yours? I'll still publish the merged version so people don't try installing this one and get errors.

**Comment by pluscubed** [comment]
I see that preact-cli will have this built-in: developit/preact-cli#617 🎉🎉🎉

I suppose I'll just keep my plugin up alongside this one and mark them both as deprecated when the update comes out.
